# Generated by Django 5.1.7 on 2025-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('social', 'Social'), ('sports', 'Sports'), ('clubs', 'Clubs')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='community',
            field=models.CharField(choices=[('cs101', 'CS101'), ('drama_club', 'Drama Club'), ('football_team', 'Football Team'), ('debate_society', 'Debate Society')], default='cs101', max_length=20),
        ),
    ]
