# Generated by Django 5.1.7 on 2025-05-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
    ]
