# Generated by Django 5.1.7 on 2025-05-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='community',
        ),
    ]
