# Generated by Django 5.1.7 on 2025-05-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_event_community'),
        ('api', '0006_remove_profile_is_complete'),
    ]

    operations = [
    ]
