# Generated by Django 5.1.7 on 2025-05-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_community_slug'),
        ('api', '0007_merge_20250507_2350'),
        ('api', '0007_merge_20250508_0002'),
    ]

    operations = [
    ]
