# Generated by Django 5.1.7 on 2025-05-08 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250508_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.community'),
        ),
    ]
