# Generated by Django 5.1.7 on 2025-05-08 01:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_profile_year_profile_address_profile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_pic_upload_path),
        ),
    ]
