# Generated by Django 5.1.7 on 2025-05-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_note_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='communities', to='api.tag'),
        ),
    ]
