# Generated by Django 5.1.7 on 2025-05-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_profile_pic'),
        ('api', '0010_tag_community_tags'),
    ]

    operations = [
    ]
