# Generated by Django 5.1.7 on 2025-05-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
