# Generated by Django 5.1.7 on 2025-05-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250508_0316'),
        ('api', '0013_friendrequest'),
    ]

    operations = [
    ]
