# Generated by Django 5.2.1 on 2025-05-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_0011_merge_20250508_0316_0013_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_global_admin',
            field=models.BooleanField(default=False),
        ),
    ]
