# Generated by Django 5.2.1 on 2025-05-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_friendrequest_unique_together'),
        ('api', '0015_profile_is_global_admin'),
    ]

    operations = [
    ]
