# Generated by Django 5.2.1 on 2025-05-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20250508_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('arts', 'Arts'), ('wellness', 'Wellness'), ('career', 'Career'), ('technology', 'Technology'), ('volunteering', 'Volunteering'), ('housing', 'Housing'), ('social', 'Social'), ('sports', 'Sports'), ('clubs', 'Clubs')], default='academic', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('arts', 'Arts'), ('wellness', 'Wellness'), ('career', 'Career'), ('technology', 'Technology'), ('volunteering', 'Volunteering'), ('housing', 'Housing'), ('social', 'Social'), ('sports', 'Sports'), ('clubs', 'Clubs')], default='academic', max_length=20),
        ),
    ]
