# Generated by Django 5.2.1 on 2025-05-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_community_category_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='required_materials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
