# Generated by Django 5.2.1 on 2025-05-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_max_capacity_event_required_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.community'),
        ),
    ]
