# Generated by Django 5.2.1 on 2025-05-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20250508_0517'),
        ('api', '0019_event_community'),
    ]

    operations = [
    ]
